server:
  port: 8082
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    requests: "/api/v1/solicitud"
    requests-with-id: "/api/v1/solicitud/{id}/{action}"
    
#adapters:
#  r2dbc:
#    host: ${SPRING_R2DBC_HOST:p_solicitudes}
#    port: ${SPRING_R2DBC_PORT:5432}
#    database: ${SPRING_R2DBC_DATABASE:p_solicitudes}
#    schema: ${SPRING_R2DBC_SCHEMA:public}
#    username: ${SPRING_R2DBC_USERNAME:postgres}
#    password: ${SPRING_R2DBC_PASSWORD:1234}

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "p_solicitudes"
    schema: "public"
    username: "postgres"
    password: "1234"
services:
  auth:
    base-url: http://localhost:8081
    endpoints:
      get-user: "/api/v1/usuarios/"
